/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.CorreoDAO;
import biblioteca.tda.modelo.Correo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JDCorreo extends javax.swing.JDialog {
    String [][] matrizCorreo = new String[150][3];
    DefaultTableModel modelo;
    /**
     * Creates new form JDCorreo
     */
    public JDCorreo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtIdListaCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarCorreo = new javax.swing.JButton();
        btnBuscarCorreo = new javax.swing.JButton();
        btnEliminarCorreo = new javax.swing.JButton();
        btnModificarCorreo = new javax.swing.JButton();
        btnListarCorreo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCorreo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Correo");

        jLabel2.setText("ID:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Lista Correo:");

        btnAgregarCorreo.setText("Agregar");
        btnAgregarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCorreoActionPerformed(evt);
            }
        });

        btnBuscarCorreo.setText("Buscar");
        btnBuscarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCorreoActionPerformed(evt);
            }
        });

        btnEliminarCorreo.setText("Eliminar");
        btnEliminarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCorreoActionPerformed(evt);
            }
        });

        btnModificarCorreo.setText("Modificar");
        btnModificarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCorreoActionPerformed(evt);
            }
        });

        btnListarCorreo.setText("Listar");
        btnListarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCorreoActionPerformed(evt);
            }
        });

        tblCorreo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "CORREO", "LISTA CORREO"
            }
        ));
        jScrollPane1.setViewportView(tblCorreo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCorreo)
                                .addComponent(txtIdListaCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(btnAgregarCorreo)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscarCorreo)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminarCorreo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnModificarCorreo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnListarCorreo))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdListaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCorreo)
                    .addComponent(btnBuscarCorreo)
                    .addComponent(btnEliminarCorreo)
                    .addComponent(btnModificarCorreo)
                    .addComponent(btnListarCorreo))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCorreoActionPerformed
        // TODO add your handling code here:
        try {
            Correo correo = new Correo();
            CorreoDAO correoDAO = new CorreoDAO();
            
            correo.setId(Integer.parseInt(txtIdCorreo.getText()));
            correo.setCorreo(txtCorreo.getText());
            correo.setListaCorreo(Integer.parseInt(txtIdListaCorreo.getText()));
            correoDAO.insertar(correo);
            JOptionPane.showMessageDialog(null, "Autor ingresado");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarCorreoActionPerformed

    private void btnBuscarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCorreoActionPerformed
        // TODO add your handling code here:
        try {
            CorreoDAO correoDAO = new CorreoDAO();
            Correo correo = correoDAO.buscar(Integer.parseInt(txtIdCorreo.getText()));
            if(correo.getId() != 0) {
                txtCorreo.setText(correo.getCorreo());
                txtIdListaCorreo.setText(String.valueOf(correo.getListaCorreo()));
                
            } else {
                JOptionPane.showMessageDialog(null, "Correo no encontrado");
                limpiarControles();
                txtIdCorreo.requestFocus();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarCorreoActionPerformed

    private void btnEliminarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCorreoActionPerformed
        // TODO add your handling code here:
        try {
            CorreoDAO correoDAO = new CorreoDAO();
            if(correoDAO.eliminar(Integer.parseInt(txtIdCorreo.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Correo Eliminado");
                limpiarControles();
                txtIdCorreo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró correo para eliminar");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarCorreoActionPerformed

    private void btnModificarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCorreoActionPerformed
        // TODO add your handling code here:
        try {
            Correo correo = new Correo();
            CorreoDAO correoDAO = new CorreoDAO();
            
            correo.setId(Integer.parseInt(txtIdCorreo.getText()));
            correo.setCorreo(txtCorreo.getText());
            correo.setListaCorreo(Integer.parseInt(txtIdListaCorreo.getText()));
            correoDAO.modificar(correo);
            JOptionPane.showMessageDialog(null, "Correo Modificado");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarCorreoActionPerformed

    private void btnListarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCorreoActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            CorreoDAO correoDAO = new CorreoDAO();
            String[] titulos = {"ID", "CORREO", "LISTA CORREO"};
            ArrayList<Correo> lista = correoDAO.listar();
            for(Correo correo : lista) {
                matrizCorreo[fila][0] = String.valueOf(correo.getId());
                matrizCorreo[fila][1] = correo.getCorreo();
                matrizCorreo[fila][2] = String.valueOf(correo.getListaCorreo());
                fila++;
            }
            modelo = new DefaultTableModel(matrizCorreo, titulos);
            tblCorreo.setModel(modelo);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarCorreoActionPerformed

    public void limpiarControles() {
        txtIdCorreo.setText("");
        txtCorreo.setText("");
        txtIdListaCorreo.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCorreo dialog = new JDCorreo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCorreo;
    private javax.swing.JButton btnBuscarCorreo;
    private javax.swing.JButton btnEliminarCorreo;
    private javax.swing.JButton btnListarCorreo;
    private javax.swing.JButton btnModificarCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdCorreo;
    private javax.swing.JTextField txtIdListaCorreo;
    // End of variables declaration//GEN-END:variables
}
