/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.CiudadDAO;
import biblioteca.tda.dao.RegionDAO;
import biblioteca.tda.modelo.Ciudad;
import biblioteca.tda.modelo.Region;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFCiudad extends javax.swing.JFrame {
    String [][] matrizCiudad = new String[150][3];
    DefaultTableModel modelo;
    /**
     * Creates new form JFCiudad
     */
    public JFCiudad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCiudad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreRegion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdRegion = new javax.swing.JTextField();
        btnBuscarRegion = new javax.swing.JButton();
        btnAgregarCiudad = new javax.swing.JButton();
        btnBuscarCiudad = new javax.swing.JButton();
        btnEliminarCiudad = new javax.swing.JButton();
        btnModificarCiudad = new javax.swing.JButton();
        btnListarCiudad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCiudad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CIUDAD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ciudad");

        jLabel2.setText("ID Ciudad:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("ID Region:");

        jLabel5.setText("Region:");

        btnBuscarRegion.setText("Buscar");
        btnBuscarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRegionActionPerformed(evt);
            }
        });

        btnAgregarCiudad.setText("Agregar");
        btnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCiudadActionPerformed(evt);
            }
        });

        btnBuscarCiudad.setText("Buscar");
        btnBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCiudadActionPerformed(evt);
            }
        });

        btnEliminarCiudad.setText("Eliminar");
        btnEliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCiudadActionPerformed(evt);
            }
        });

        btnModificarCiudad.setText("Modificar");
        btnModificarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCiudadActionPerformed(evt);
            }
        });

        btnListarCiudad.setText("Listar");
        btnListarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCiudadActionPerformed(evt);
            }
        });

        tblCiudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "REGION_ID"
            }
        ));
        tblCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCiudadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCiudad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnListarCiudad))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarRegion))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIdCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(txtIdRegion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarRegion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCiudad)
                    .addComponent(btnBuscarCiudad)
                    .addComponent(btnEliminarCiudad)
                    .addComponent(btnModificarCiudad)
                    .addComponent(btnListarCiudad))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRegionActionPerformed
        // TODO add your handling code here:
        try {
            RegionDAO regionDAO = new RegionDAO();
            Region region = regionDAO.buscar(txtNombreRegion.getText());
            if(region.getId() != 0) {
                txtIdRegion.setText(String.valueOf(region.getId()));
            } else {
                JOptionPane.showMessageDialog(null, "Region no encontrada");
                limpiarControles();
                txtIdRegion.requestFocus();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnBuscarRegionActionPerformed

    private void btnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCiudadActionPerformed
        // TODO add your handling code here:
        try {
            Ciudad ciudad = new Ciudad();
            CiudadDAO ciudadDAO = new CiudadDAO();
            ciudad.setId(Integer.parseInt(txtIdCiudad.getText()));
            ciudad.setNombre(txtNombreCiudad.getText());
            ciudad.setRegionId(Integer.parseInt(txtIdRegion.getText()));
            ciudadDAO.insertar(ciudad);
            JOptionPane.showMessageDialog(null, "Ciudad ingresada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        
    }//GEN-LAST:event_btnAgregarCiudadActionPerformed

    private void btnBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCiudadActionPerformed
        // TODO add your handling code here:
        try {
            RegionDAO regionDAO = new RegionDAO();
            
   
            CiudadDAO ciudadDAO = new CiudadDAO();
            Ciudad ciudad = ciudadDAO.buscar(Integer.parseInt(txtIdCiudad.getText()));
            if(ciudad.getId() != 0) {
                Region region = regionDAO.buscar(Integer.parseInt(txtIdRegion.getText()));
                txtNombreCiudad.setText(ciudad.getNombre());
                txtIdRegion.setText(String.valueOf(ciudad.getRegionId()));
                txtNombreRegion.setText(region.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "Ciudad no encontrada");
                limpiarControles();
                txtIdCiudad.requestFocus();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarCiudadActionPerformed

    private void btnEliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCiudadActionPerformed
        // TODO add your handling code here:
        
        try {
            CiudadDAO ciudadDAO = new CiudadDAO();
            if(ciudadDAO.eliminar(Integer.parseInt(txtIdCiudad.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Ciudad Eliminada");
                limpiarControles();
                txtIdCiudad.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró ciudad para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarCiudadActionPerformed

    private void btnModificarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCiudadActionPerformed
        // TODO add your handling code here:
        try {
            Ciudad ciudad = new Ciudad();
            CiudadDAO ciudadDAO = new CiudadDAO();
            
            ciudad.setId(Integer.parseInt(txtIdCiudad.getText()));
            ciudad.setNombre(txtNombreCiudad.getText());
            ciudad.setRegionId(Integer.parseInt(txtIdRegion.getText()));
            ciudadDAO.modificar(ciudad);
            JOptionPane.showMessageDialog(null, "Ciudad Modificada");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarCiudadActionPerformed

    private void btnListarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCiudadActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            CiudadDAO ciudadDAO = new CiudadDAO();
            String[] titulos = {"ID CIUDAD", "NOMBRE CIUDAD", "ID REGION"};
            ArrayList<Ciudad> lista = ciudadDAO.listar();
            for(Ciudad ciudad : lista) {
                matrizCiudad[fila][0] = String.valueOf(ciudad.getId());
                matrizCiudad[fila][1] = ciudad.getNombre();
                matrizCiudad[fila][2] = String.valueOf(ciudad.getRegionId());
                fila++;
            }
            modelo = new DefaultTableModel(matrizCiudad, titulos);
            tblCiudad.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarCiudadActionPerformed

    private void tblCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCiudadMouseClicked
        // TODO add your handling code here:
        int fila = tblCiudad.getSelectedRow();
        txtIdCiudad.setText(tblCiudad.getValueAt(fila, 0).toString());
        txtNombreCiudad.setText(tblCiudad.getValueAt(fila, 1).toString());
        txtIdRegion.setText(tblCiudad.getValueAt(fila, 2).toString());;
    }//GEN-LAST:event_tblCiudadMouseClicked

    public void limpiarControles() {
        txtIdRegion.setText("");
        txtNombreRegion.setText("");
        txtNombreCiudad.setText("");
        txtIdCiudad.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCiudad().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCiudad;
    private javax.swing.JButton btnBuscarCiudad;
    private javax.swing.JButton btnBuscarRegion;
    private javax.swing.JButton btnEliminarCiudad;
    private javax.swing.JButton btnListarCiudad;
    private javax.swing.JButton btnModificarCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCiudad;
    private javax.swing.JTextField txtIdCiudad;
    private javax.swing.JTextField txtIdRegion;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtNombreRegion;
    // End of variables declaration//GEN-END:variables
}
