/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.CiudadDAO;
import biblioteca.tda.dao.ComunaDAO;
import biblioteca.tda.modelo.Ciudad;
import biblioteca.tda.modelo.Comuna;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFComuna extends javax.swing.JFrame {

    String[][] matrizComuna = new String[150][3];
    DefaultTableModel modelo;

    /**
     * Creates new form JFComuna
     */
    public JFComuna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarComuna = new javax.swing.JButton();
        btnBuscarComuna = new javax.swing.JButton();
        btnBuscarCiudad = new javax.swing.JButton();
        btnEliminarComuna = new javax.swing.JButton();
        btnModificarComuna = new javax.swing.JButton();
        btnListarComuna = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComuna = new javax.swing.JTable();
        txtNombreCiudad = new javax.swing.JTextField();
        txtIdCiudad = new javax.swing.JTextField();
        txtIdComuna = new javax.swing.JTextField();
        txtNombreComuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Comuna");

        jLabel2.setText("ID Comuna:");

        jLabel3.setText("Nombre Comuna:");

        jLabel4.setText("Nombre Ciudad:");

        jLabel5.setText("ID Ciudad:");

        btnAgregarComuna.setText("Agregar");
        btnAgregarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComunaActionPerformed(evt);
            }
        });

        btnBuscarComuna.setText("Buscar");
        btnBuscarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComunaActionPerformed(evt);
            }
        });

        btnBuscarCiudad.setText("Buscar");
        btnBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCiudadActionPerformed(evt);
            }
        });

        btnEliminarComuna.setText("Eliminar");
        btnEliminarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComunaActionPerformed(evt);
            }
        });

        btnModificarComuna.setText("Modificar");
        btnModificarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComunaActionPerformed(evt);
            }
        });

        btnListarComuna.setText("Listar");
        btnListarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarComunaActionPerformed(evt);
            }
        });

        tblComuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "ID CIUDAD"
            }
        ));
        tblComuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblComuna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarComuna)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarComuna)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarComuna)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarComuna)
                                .addGap(26, 26, 26)
                                .addComponent(btnListarComuna))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCiudad)
                            .addComponent(txtIdCiudad)
                            .addComponent(txtIdComuna)
                            .addComponent(txtNombreComuna, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarCiudad)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCiudad))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarComuna)
                    .addComponent(btnBuscarComuna)
                    .addComponent(btnEliminarComuna)
                    .addComponent(btnModificarComuna)
                    .addComponent(btnListarComuna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCiudadActionPerformed
        // TODO add your handling code here:
        try {
            CiudadDAO ciudadDAO = new CiudadDAO();
            Ciudad ciudad = ciudadDAO.buscar(txtNombreCiudad.getText());
            if (ciudad.getId() != 0) {
                txtIdCiudad.setText(String.valueOf(ciudad.getId()));

            } else {
                JOptionPane.showMessageDialog(null, "Ciudad no encontrada");
                limpiarControles();
                txtIdCiudad.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarCiudadActionPerformed

    private void btnAgregarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComunaActionPerformed
        // TODO add your handling code here:
        try {
            Comuna comuna = new Comuna();
            ComunaDAO comunaDAO = new ComunaDAO();
            comuna.setId(Integer.parseInt(txtIdComuna.getText()));
            comuna.setNombre(txtNombreComuna.getText());
            comuna.setCiudadId(Integer.parseInt(txtIdCiudad.getText()));
            comunaDAO.insertar(comuna);
            JOptionPane.showMessageDialog(null, "Comuna ingresada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarComunaActionPerformed

    private void btnBuscarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComunaActionPerformed
        // TODO add your handling code here:
        try {
            CiudadDAO ciudadDAO = new CiudadDAO();

            ComunaDAO comunaDAO = new ComunaDAO();
            Comuna comuna = comunaDAO.buscar(Integer.parseInt(txtIdCiudad.getText()));
            if (comuna.getId() != 0) {
                Ciudad ciudad = ciudadDAO.buscar(Integer.parseInt(txtIdCiudad.getText()));
                txtNombreComuna.setText(comuna.getNombre());
                txtIdCiudad.setText(String.valueOf(ciudad.getId()));
                txtNombreCiudad.setText(ciudad.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "Comuna no encontrada");
                limpiarControles();
                txtIdComuna.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarComunaActionPerformed

    private void btnEliminarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComunaActionPerformed
        // TODO add your handling code here:
        try {
            ComunaDAO comunaDAO = new ComunaDAO();
            if (comunaDAO.eliminar(Integer.parseInt(txtIdComuna.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Comuna Eliminada");
                limpiarControles();
                txtIdComuna.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró comuna para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarComunaActionPerformed

    private void btnModificarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComunaActionPerformed
        // TODO add your handling code here:
        try {
            Comuna comuna = new Comuna();
            ComunaDAO comunaDAO = new ComunaDAO();

            comuna.setId(Integer.parseInt(txtIdComuna.getText()));
            comuna.setNombre(txtNombreComuna.getText());
            comuna.setCiudadId(Integer.parseInt(txtIdCiudad.getText()));
            comunaDAO.modificar(comuna);
            JOptionPane.showMessageDialog(null, "Comuna Modificada");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarComunaActionPerformed

    private void btnListarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarComunaActionPerformed
        // TODO add your handling code here:
        try {

            int fila = 0;
            ComunaDAO comunaDAO = new ComunaDAO();
            String[] titulos = {"ID COMUNA", "NOMBRE COMUNA", "ID CIUDAD"};
            ArrayList<Comuna> lista = comunaDAO.listar();
            for (Comuna comuna : lista) {
                matrizComuna[fila][0] = String.valueOf(comuna.getId());
                matrizComuna[fila][1] = comuna.getNombre();
                matrizComuna[fila][2] = String.valueOf(comuna.getCiudadId());
                fila++;
            }
            modelo = new DefaultTableModel(matrizComuna, titulos);
            tblComuna.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarComunaActionPerformed

    private void tblComunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComunaMouseClicked
        // TODO add your handling code here:
        int fila = tblComuna.getSelectedRow();
        txtIdComuna.setText(tblComuna.getValueAt(fila, 0).toString());
        txtNombreComuna.setText(tblComuna.getValueAt(fila, 1).toString());
        txtIdCiudad.setText(tblComuna.getValueAt(fila, 2).toString());
        
    }//GEN-LAST:event_tblComunaMouseClicked

    public void limpiarControles() {
        txtIdComuna.setText("");
        txtNombreComuna.setText("");
        txtNombreCiudad.setText("");
        txtIdCiudad.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFComuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComuna;
    private javax.swing.JButton btnBuscarCiudad;
    private javax.swing.JButton btnBuscarComuna;
    private javax.swing.JButton btnEliminarComuna;
    private javax.swing.JButton btnListarComuna;
    private javax.swing.JButton btnModificarComuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComuna;
    private javax.swing.JTextField txtIdCiudad;
    private javax.swing.JTextField txtIdComuna;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtNombreComuna;
    // End of variables declaration//GEN-END:variables
}
