/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.EditorialDAO;
import biblioteca.tda.modelo.Editorial;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFEditorial extends javax.swing.JFrame {
    String [][] matrizEditorial = new String[150][2];
    DefaultTableModel modelo;
    /**
     * Creates new form JFEditorial
     */
    public JFEditorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEditorial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEditorial = new javax.swing.JTextField();
        btnAgregarEditorial = new javax.swing.JButton();
        btnBuscarEditorial = new javax.swing.JButton();
        btnEliminarEditorial = new javax.swing.JButton();
        btnModificarEditorial = new javax.swing.JButton();
        btnListarEditorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Editorial");

        jLabel2.setText("ID Editorial:");

        jLabel3.setText("Nombre:");

        btnAgregarEditorial.setText("Agregar");
        btnAgregarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEditorialActionPerformed(evt);
            }
        });

        btnBuscarEditorial.setText("Buscar");
        btnBuscarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEditorialActionPerformed(evt);
            }
        });

        btnEliminarEditorial.setText("Eliminar");
        btnEliminarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEditorialActionPerformed(evt);
            }
        });

        btnModificarEditorial.setText("Modificar");
        btnModificarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEditorialActionPerformed(evt);
            }
        });

        btnListarEditorial.setText("Listar");
        btnListarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEditorialActionPerformed(evt);
            }
        });

        tblEditorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NOMBRE"
            }
        ));
        tblEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditorialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAgregarEditorial)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarEditorial)
                                .addGap(34, 34, 34)
                                .addComponent(btnEliminarEditorial)
                                .addGap(31, 31, 31)
                                .addComponent(btnModificarEditorial)
                                .addGap(28, 28, 28)
                                .addComponent(btnListarEditorial))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdEditorial)
                                    .addComponent(txtNombreEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEditorial)
                    .addComponent(btnBuscarEditorial)
                    .addComponent(btnEliminarEditorial)
                    .addComponent(btnModificarEditorial)
                    .addComponent(btnListarEditorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEditorialActionPerformed
        // TODO add your handling code here:
        try{
            Editorial editorial = new Editorial();
            EditorialDAO editorialDAO = new EditorialDAO();
            
            editorial.setId(Integer.parseInt(txtIdEditorial.getText()));
            editorial.setNombre(txtNombreEditorial.getText());
            editorialDAO.insertar(editorial);
            JOptionPane.showMessageDialog(null, "Editorial ingresada");
            limpiarControles();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnAgregarEditorialActionPerformed

    private void btnBuscarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEditorialActionPerformed
        // TODO add your handling code here:
        try{
            EditorialDAO editorialDAO = new EditorialDAO();
            Editorial editorial = editorialDAO.buscar(Integer.parseInt(txtIdEditorial.getText()));
            if(editorial.getId() != 0) {
                txtNombreEditorial.setText(editorial.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "Estado no encontrado");
                limpiarControles();
                txtIdEditorial.requestFocus();
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarEditorialActionPerformed

    private void btnEliminarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEditorialActionPerformed
        // TODO add your handling code here:
        try {
            EditorialDAO editorialDAO = new EditorialDAO();
            if(editorialDAO.eliminar(Integer.parseInt(txtIdEditorial.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Editorial Eliminado");
                limpiarControles();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró editorial para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarEditorialActionPerformed

    private void btnModificarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEditorialActionPerformed
        // TODO add your handling code here:
        
        try {
            Editorial editorial = new Editorial();
            EditorialDAO editorialDAO = new EditorialDAO();
            
            editorial.setId(Integer.parseInt(txtIdEditorial.getText()));
            editorial.setNombre(txtNombreEditorial.getText());
            editorialDAO.modificar(editorial);
            JOptionPane.showMessageDialog(null, "Idioma Modificado");
            limpiarControles();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarEditorialActionPerformed

    private void btnListarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEditorialActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            EditorialDAO editorialDAO = new EditorialDAO();
            String[] titulos = {"ID", "NOMBRE"};
            ArrayList<Editorial> lista = editorialDAO.listarEditorial();
            for(Editorial editorial : lista) {
                matrizEditorial[fila][0] = String.valueOf(editorial.getId());
                matrizEditorial[fila][1] = editorial.getNombre();
                fila++;
            }
            modelo = new DefaultTableModel(matrizEditorial, titulos);
            tblEditorial.setModel(modelo);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarEditorialActionPerformed

    private void tblEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditorialMouseClicked
        // TODO add your handling code here:
        int fila = tblEditorial.getSelectedRow();
        txtIdEditorial.setText(tblEditorial.getValueAt(fila, 0).toString());
        txtNombreEditorial.setText(tblEditorial.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblEditorialMouseClicked

    public void limpiarControles() {
        txtIdEditorial.setText("");
        txtNombreEditorial.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEditorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEditorial;
    private javax.swing.JButton btnBuscarEditorial;
    private javax.swing.JButton btnEliminarEditorial;
    private javax.swing.JButton btnListarEditorial;
    private javax.swing.JButton btnModificarEditorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEditorial;
    private javax.swing.JTextField txtIdEditorial;
    private javax.swing.JTextField txtNombreEditorial;
    // End of variables declaration//GEN-END:variables
}
