/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.IdiomaDAO;
import biblioteca.tda.modelo.Idioma;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFIdioma extends javax.swing.JFrame {
    String [][] matrizIdioma = new String[150][2];
    DefaultTableModel modelo;
    /**
     * Creates new form JFIdioma
     */
    public JFIdioma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdIdioma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        btnGuardarIdioma = new javax.swing.JButton();
        btnBuscarIdioma = new javax.swing.JButton();
        btnEliminarIdioma = new javax.swing.JButton();
        btnModificarIdioma = new javax.swing.JButton();
        btnListarIdioma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIdioma = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IDIOMA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Idioma");

        jLabel3.setText("ID Idioma:");

        jLabel4.setText("Idioma: ");

        btnGuardarIdioma.setText("Guardar");
        btnGuardarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIdiomaActionPerformed(evt);
            }
        });

        btnBuscarIdioma.setText("Buscar");
        btnBuscarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdiomaActionPerformed(evt);
            }
        });

        btnEliminarIdioma.setText("Eliminar");
        btnEliminarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIdiomaActionPerformed(evt);
            }
        });

        btnModificarIdioma.setText("Modificar");
        btnModificarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarIdiomaActionPerformed(evt);
            }
        });

        btnListarIdioma.setText("Listar");
        btnListarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarIdiomaActionPerformed(evt);
            }
        });

        tblIdioma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido"
            }
        ));
        tblIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIdiomaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIdioma);
        if (tblIdioma.getColumnModel().getColumnCount() > 0) {
            tblIdioma.getColumnModel().getColumn(0).setPreferredWidth(14);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarIdioma)
                                .addGap(37, 37, 37)
                                .addComponent(btnBuscarIdioma)
                                .addGap(38, 38, 38)
                                .addComponent(btnEliminarIdioma)
                                .addGap(36, 36, 36)
                                .addComponent(btnModificarIdioma)
                                .addGap(37, 37, 37)
                                .addComponent(btnListarIdioma))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtIdIdioma))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarIdioma)
                    .addComponent(btnGuardarIdioma)
                    .addComponent(btnEliminarIdioma)
                    .addComponent(btnModificarIdioma)
                    .addComponent(btnListarIdioma))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIdiomaActionPerformed
        // TODO add your handling code here:
        try {
            Idioma idioma = new Idioma();
            IdiomaDAO idiomaDao = new IdiomaDAO();

            idioma.setId(Integer.parseInt(txtIdIdioma.getText()));
            idioma.setIdioma(txtIdioma.getText());
            idiomaDao.insertar(idioma);
            JOptionPane.showMessageDialog(null, "Idioma ingresado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnGuardarIdiomaActionPerformed

    private void btnBuscarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdiomaActionPerformed
        // TODO add your handling code here:

        try {
            IdiomaDAO idiomaDao = new IdiomaDAO();
            Idioma idioma = idiomaDao.buscar(Integer.parseInt(txtIdIdioma.getText()));
            if(idioma.getId() != 0) {
                txtIdioma.setText(idioma.getIdioma());
            } else {
                JOptionPane.showMessageDialog(null, "Idioma no encontrado");
                limpiarControles();
                txtIdIdioma.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarIdiomaActionPerformed

    private void btnEliminarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIdiomaActionPerformed
        // TODO add your handling code here:
        try {
            IdiomaDAO idiomaDao = new IdiomaDAO();
            if(idiomaDao.eliminar(Integer.parseInt(txtIdIdioma.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Idioma Eliminado");
                limpiarControles();
                txtIdIdioma.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró idioma para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarIdiomaActionPerformed

    private void btnModificarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarIdiomaActionPerformed
        // TODO add your handling code here:
        try {
            Idioma idioma = new Idioma();
            IdiomaDAO idiomaDao = new IdiomaDAO();

            idioma.setId(Integer.parseInt(txtIdIdioma.getText()));
            idioma.setIdioma(txtIdioma.getText());
            idiomaDao.modificar(idioma);
            JOptionPane.showMessageDialog(null, "Idioma Modificado");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarIdiomaActionPerformed

    private void btnListarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarIdiomaActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            IdiomaDAO idiomaDao = new IdiomaDAO();
            String [] titulos = {"ID", "IDIOMA"};
            ArrayList<Idioma> lista = idiomaDao.listar();
            for(Idioma idioma : lista) {
                matrizIdioma[fila][0] = String.valueOf(idioma.getId());
                matrizIdioma[fila][1] = idioma.getIdioma();
                fila++;
            }
            modelo = new DefaultTableModel(matrizIdioma, titulos);
            tblIdioma.setModel(modelo);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarIdiomaActionPerformed

    private void tblIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIdiomaMouseClicked
        // TODO add your handling code here:
        int fila = tblIdioma.getSelectedRow();
        txtIdIdioma.setText(tblIdioma.getValueAt(fila, 0).toString());
        txtIdioma.setText(tblIdioma.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblIdiomaMouseClicked

    public void limpiarControles() {
        txtIdIdioma.setText("");
        txtIdioma.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFIdioma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIdioma;
    private javax.swing.JButton btnEliminarIdioma;
    private javax.swing.JButton btnGuardarIdioma;
    private javax.swing.JButton btnListarIdioma;
    private javax.swing.JButton btnModificarIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIdioma;
    private javax.swing.JTextField txtIdIdioma;
    private javax.swing.JTextField txtIdioma;
    // End of variables declaration//GEN-END:variables
}
