/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.LibroDAO;
import biblioteca.tda.modelo.Libro;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFLibro extends javax.swing.JFrame {

    String[][] matrizLibro = new String[100][12];
    DefaultTableModel modelo;

    /**
     * Creates new form JFLibro
     */
    public JFLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDeSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroPaginas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioReferencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateAnioLanzamiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        datePublicacion = new com.toedter.calendar.JDateChooser();
        btnBuscarCategoria = new javax.swing.JButton();
        btnBuscarAutor = new javax.swing.JButton();
        btnBuscarEditorial = new javax.swing.JButton();
        btnBuscarIdioma = new javax.swing.JButton();
        btnBuscarEstado = new javax.swing.JButton();
        btnAgregarLibro = new javax.swing.JButton();
        btnBuscarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnModificarLibro = new javax.swing.JButton();
        btnListarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtIdCategoria = new javax.swing.JTextField();
        txtIdAutor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIdEditorial = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtIdIdioma = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIdEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIBRO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Libro");

        jLabel2.setText("Numero de Serie:");

        jLabel3.setText("Título:");

        jLabel4.setText("Número de Páginas:");

        jLabel5.setText("Precio Referencia:");

        jLabel6.setText("Año Lanzamiento:");

        jLabel7.setText("Publicacion:");

        btnBuscarCategoria.setText("Buscar");
        btnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCategoriaActionPerformed(evt);
            }
        });

        btnBuscarAutor.setText("Buscar");
        btnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorActionPerformed(evt);
            }
        });

        btnBuscarEditorial.setText("Buscar");
        btnBuscarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEditorialActionPerformed(evt);
            }
        });

        btnBuscarIdioma.setText("Buscar");
        btnBuscarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdiomaActionPerformed(evt);
            }
        });

        btnBuscarEstado.setText("Buscar");
        btnBuscarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstadoActionPerformed(evt);
            }
        });

        btnAgregarLibro.setText("Agregar");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        btnModificarLibro.setText("Modificar");
        btnModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLibroActionPerformed(evt);
            }
        });

        btnListarLibro.setText("Listar");
        btnListarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLibroActionPerformed(evt);
            }
        });

        tblLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "N° SERIE", "Titulo", "N° Páginas", "Precio Referencia", "Publicacón", "Año Lanzamiento", "Categoría", "Autor", "Editorial", "Idioma", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblLibro);
        if (tblLibro.getColumnModel().getColumnCount() > 0) {
            tblLibro.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel13.setText("ID Libro:");

        jLabel14.setText("ID Categoria:");

        jLabel15.setText("ID Autor:");

        jLabel16.setText("ID Editorial");

        jLabel17.setText("ID Idioma:");

        jLabel18.setText("ID Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(btnAgregarLibro)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnBuscarLibro)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnEliminarLibro)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnModificarLibro)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnListarLibro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNumeroDeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPrecioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(datePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dateAnioLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCategoria)
                            .addComponent(txtIdAutor)
                            .addComponent(txtIdEditorial)
                            .addComponent(txtIdIdioma)
                            .addComponent(txtIdEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarAutor)
                            .addComponent(btnBuscarEditorial)
                            .addComponent(btnBuscarIdioma)
                            .addComponent(btnBuscarEstado)
                            .addComponent(btnBuscarCategoria))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroDeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateAnioLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(datePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCategoria))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarAutor))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarEditorial)
                            .addComponent(jLabel16)
                            .addComponent(txtIdEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarIdioma)
                            .addComponent(jLabel17)
                            .addComponent(txtIdIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarEstado)
                            .addComponent(jLabel18)
                            .addComponent(txtIdEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLibro)
                    .addComponent(btnBuscarLibro)
                    .addComponent(btnEliminarLibro)
                    .addComponent(btnModificarLibro)
                    .addComponent(btnListarLibro))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed
        // TODO add your handling code here:
        JDBuscarCategoria jdBuscarCategoria = new JDBuscarCategoria(this, true);
        jdBuscarCategoria.setVisible(true);
        while (jdBuscarCategoria.sw == 0) {
            txtIdCategoria.setText("");
        }

        txtIdCategoria.setText(String.valueOf(jdBuscarCategoria.categoria.getId()));


    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        // TODO add your handling code here:
        JDBuscarAutor jdBuscarAutor = new JDBuscarAutor(this, true);
        jdBuscarAutor.setVisible(true);
        if (jdBuscarAutor.sw == 0) {
            txtIdAutor.setText("");
        }
        txtIdAutor.setText(String.valueOf(jdBuscarAutor.autor.getId()));

    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    private void btnBuscarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEditorialActionPerformed
        // TODO add your handling code here:
        JDBuscarEditorial jdBuscarEditorial = new JDBuscarEditorial(this, true);
        jdBuscarEditorial.setVisible(true);
        if (jdBuscarEditorial.sw == 0) {
            txtIdEditorial.setText("");
        }
        txtIdEditorial.setText(String.valueOf(jdBuscarEditorial.editorial.getId()));

    }//GEN-LAST:event_btnBuscarEditorialActionPerformed

    private void btnBuscarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdiomaActionPerformed
        // TODO add your handling code here:
        JDIdioma jdBuscarIdioma = new JDIdioma(this, true);
        jdBuscarIdioma.setVisible(true);
        if (jdBuscarIdioma.sw == 0) {
            txtIdIdioma.setText("");
        }

        txtIdIdioma.setText(String.valueOf(jdBuscarIdioma.idioma.getId()));
    }//GEN-LAST:event_btnBuscarIdiomaActionPerformed

    private void btnBuscarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstadoActionPerformed
        // TODO add your handling code here:
        JDEstado jdBuscarEstado = new JDEstado(this, true);
        jdBuscarEstado.setVisible(true);
        if (jdBuscarEstado.sw == 0) {
            txtIdEstado.setText("");
        }
        txtIdEstado.setText(String.valueOf(jdBuscarEstado.estado.getId()));

    }//GEN-LAST:event_btnBuscarEstadoActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        try {
            Libro libro = new Libro();
            LibroDAO libroDAO = new LibroDAO();

            libro.setId(Integer.parseInt(txtIdLibro.getText()));
            libro.setNumeroSerie(txtNumeroDeSerie.getText());
            libro.setTitulo(txtTituloLibro.getText());
            libro.setNumeroPaginas(Integer.parseInt(txtNumeroPaginas.getText()));
            libro.setPrecioReferencia(Integer.parseInt(txtPrecioReferencia.getText()));
            String anioLanzamientoString = new String();
            // rescatamos la fecha para convertir a SQL
            long anioLanzamientoDate = (dateAnioLanzamiento.getDate().getTime());
            // Convertimos a SQL
            java.sql.Date anioLanzamientoSQL = new java.sql.Date(anioLanzamientoDate);
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            // De SQL a String
            anioLanzamientoString = df.format(anioLanzamientoSQL);
            libro.setAnoLanzamiento(anioLanzamientoString);
            long publicacionDate = (datePublicacion.getDate().getTime());
            String anioPublicacion = new String();
            java.sql.Date publicacionSQL = new java.sql.Date(publicacionDate);
            anioPublicacion = df.format(publicacionSQL);
            libro.setPublicacion(anioPublicacion);
            libro.setCategoria(Integer.parseInt(txtIdCategoria.getText()));
            libro.setEstado(Integer.parseInt(txtIdEstado.getText()));
            libro.setEditorial(Integer.parseInt(txtIdEditorial.getText()));
            libro.setIdioma(Integer.parseInt(txtIdIdioma.getText()));
            libro.setAutor(Integer.parseInt(txtIdAutor.getText()));
            libroDAO.insertar(libro);
            JOptionPane.showMessageDialog(null, "Libro ingresado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:

        try {
            LibroDAO libroDAO = new LibroDAO();
            Libro libro = libroDAO.buscar(Integer.parseInt(txtIdLibro.getText()));
            if (libro.getId() != 0) {
                txtIdLibro.setText(String.valueOf(libro.getId()));
                txtNumeroDeSerie.setText(libro.getNumeroSerie());
                txtTituloLibro.setText(libro.getTitulo());
                txtNumeroPaginas.setText(String.valueOf(libro.getNumeroPaginas()));
                txtPrecioReferencia.setText(String.valueOf(libro.getPrecioReferencia()));
                // parseamos el formato
                //DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                // creamos un string para almacenar la nueva fecha con el nuevo formato
                //String anioLanzamiento = df.format(libro.getAnoLanzamiento());
                // parseamos a date
                //Date anioLanzamientoDate = new SimpleDateFormat("dd/MM/yyyy").parse(anioLanzamiento);
                // asignamos a la variable
                //dateAnioLanzamiento.setDate(anioLanzamientoDate);
                //String anioPublicacion = df.format(libro.getPublicacion());
                //Date anioPublicacionDate = new SimpleDateFormat("dd/MM/yyyy").parse(anioPublicacion);
                //datePublicacion.setDate(anioPublicacionDate);
                txtIdCategoria.setText(String.valueOf(libro.getCategoria()));
                txtIdAutor.setText(String.valueOf(libro.getAutor()));
                txtIdIdioma.setText(String.valueOf(libro.getIdioma()));
                txtIdEditorial.setText(String.valueOf(libro.getEditorial()));
                txtIdEstado.setText(String.valueOf(libro.getEstado()));

            } else {
                JOptionPane.showMessageDialog(null, "Libro no encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
        try {
            LibroDAO libroDAO = new LibroDAO();
            if (libroDAO.eliminar(Integer.parseInt(txtIdLibro.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Libro Eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró libro para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLibroActionPerformed
        // TODO add your handling code here:
        try {
            Libro libro = new Libro();
            LibroDAO libroDAO = new LibroDAO();

            libro.setId(Integer.parseInt(txtIdLibro.getText()));
            libro.setNumeroSerie(txtNumeroDeSerie.getText());
            libro.setTitulo(txtTituloLibro.getText());
            libro.setNumeroPaginas(Integer.parseInt(txtNumeroPaginas.getText()));
            libro.setPrecioReferencia(Integer.parseInt(txtPrecioReferencia.getText()));
            String anioLanzamientoString = new String();
            // rescatamos la fecha para convertir a SQL
            long anioLanzamientoDate = (dateAnioLanzamiento.getDate().getTime());
            // Convertimos a SQL
            java.sql.Date anioLanzamientoSQL = new java.sql.Date(anioLanzamientoDate);
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            // De SQL a String
            anioLanzamientoString = df.format(anioLanzamientoSQL);
            libro.setAnoLanzamiento(anioLanzamientoString);
            long publicacionDate = (datePublicacion.getDate().getTime());
            String anioPublicacion = new String();
            java.sql.Date publicacionSQL = new java.sql.Date(publicacionDate);
            anioPublicacion = df.format(publicacionSQL);
            libro.setPublicacion(anioPublicacion);
            libro.setCategoria(Integer.parseInt(txtIdCategoria.getText()));
            libro.setEstado(Integer.parseInt(txtIdEstado.getText()));
            libro.setEditorial(Integer.parseInt(txtIdEditorial.getText()));
            libro.setIdioma(Integer.parseInt(txtIdIdioma.getText()));
            libro.setAutor(Integer.parseInt(txtIdAutor.getText()));
            libroDAO.modificar(libro);
            JOptionPane.showMessageDialog(null, "Libro Modificado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarLibroActionPerformed

    private void btnListarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLibroActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            LibroDAO libroDAO = new LibroDAO();
            String[] titulos = {"ID", "N° SERIE", "TITULO", "PRECIO REF", "LANZAMIENTO","PUBLICACION", "CATEGORIA", "AUTOR", "EDITORIAL", "IDIOMA", "ESTADO"};
            ArrayList<Libro> lista = libroDAO.listarLibros();
            for(Libro libro : lista) {
                matrizLibro[fila][0] = String.valueOf(libro.getId());
                matrizLibro[fila][1] = libro.getNumeroSerie();
                matrizLibro[fila][2] = libro.getTitulo();
                matrizLibro[fila][3] = String.valueOf(libro.getPrecioReferencia());
                matrizLibro[fila][4] = libro.getAnoLanzamiento();
                matrizLibro[fila][5] = libro.getPublicacion();
                matrizLibro[fila][6] = String.valueOf(libro.getCategoria());
                matrizLibro[fila][7] = String.valueOf(libro.getAutor());
                matrizLibro[fila][8] = String.valueOf(libro.getEditorial());
                matrizLibro[fila][9] = String.valueOf(libro.getIdioma());
                matrizLibro[fila][10] = String.valueOf(libro.getEstado());
  
            }
            modelo = new DefaultTableModel(matrizLibro, titulos);
            tblLibro.setModel(modelo);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnBuscarCategoria;
    private javax.swing.JButton btnBuscarEditorial;
    private javax.swing.JButton btnBuscarEstado;
    private javax.swing.JButton btnBuscarIdioma;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnListarLibro;
    private javax.swing.JButton btnModificarLibro;
    private com.toedter.calendar.JDateChooser dateAnioLanzamiento;
    private com.toedter.calendar.JDateChooser datePublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTextField txtIdAutor;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtIdEditorial;
    private javax.swing.JTextField txtIdEstado;
    private javax.swing.JTextField txtIdIdioma;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtNumeroDeSerie;
    private javax.swing.JTextField txtNumeroPaginas;
    private javax.swing.JTextField txtPrecioReferencia;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
