/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.MetodoPagoDAO;
import biblioteca.tda.modelo.MetodoPago;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFMetodoPago extends javax.swing.JFrame {
    String [][] matrizMetodoPago = new String[150][2];
    DefaultTableModel modelo;
    
    /**
     * Creates new form JFMetodoPago
     */
    public JFMetodoPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdMetodoPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoPago = new javax.swing.JTextField();
        btnAgregarMetodoPago = new javax.swing.JButton();
        btnBuscarMetodoPago = new javax.swing.JButton();
        btnEliminarMetodoPago = new javax.swing.JButton();
        btnModificarMetodoPago = new javax.swing.JButton();
        btnListarMetodoPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMetodoPago = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Metodo Pago");

        jLabel2.setText("ID Metodo de Pago:");

        jLabel3.setText("Tipo Pago:");

        btnAgregarMetodoPago.setText("Agregar");
        btnAgregarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMetodoPagoActionPerformed(evt);
            }
        });

        btnBuscarMetodoPago.setText("Buscar");
        btnBuscarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMetodoPagoActionPerformed(evt);
            }
        });

        btnEliminarMetodoPago.setText("Eliminar");
        btnEliminarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMetodoPagoActionPerformed(evt);
            }
        });

        btnModificarMetodoPago.setText("Modificar");
        btnModificarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMetodoPagoActionPerformed(evt);
            }
        });

        btnListarMetodoPago.setText("Listar");
        btnListarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarMetodoPagoActionPerformed(evt);
            }
        });

        tblMetodoPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "TIPO PAGO"
            }
        ));
        tblMetodoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMetodoPagoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMetodoPago);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdMetodoPago)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarMetodoPago)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarMetodoPago)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarMetodoPago)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarMetodoPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListarMetodoPago)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMetodoPago)
                    .addComponent(btnBuscarMetodoPago)
                    .addComponent(btnEliminarMetodoPago)
                    .addComponent(btnModificarMetodoPago)
                    .addComponent(btnListarMetodoPago))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMetodoPagoActionPerformed
        // TODO add your handling code here:
        try {
            MetodoPago metodoPago = new MetodoPago();
            MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
            
            metodoPago.setId(Integer.parseInt(txtIdMetodoPago.getText()));
            metodoPago.setTipoPago(txtTipoPago.getText());
            metodoPagoDAO.insertar(metodoPago);
            JOptionPane.showMessageDialog(null, "Metodo Pago ingresado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnAgregarMetodoPagoActionPerformed

    private void btnBuscarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMetodoPagoActionPerformed
        // TODO add your handling code here:
        try {
            MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
            MetodoPago metodoPago = metodoPagoDAO.buscar(Integer.parseInt(txtIdMetodoPago.getText()));
            if(metodoPago.getId() != 0) {
                txtTipoPago.setText(metodoPago.getTipoPago());
            
            } else {
                JOptionPane.showMessageDialog(null, "Metodo Pago no encontrado");
                limpiarControles();
                txtIdMetodoPago.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarMetodoPagoActionPerformed

    private void btnEliminarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMetodoPagoActionPerformed
        // TODO add your handling code here:
        try {
            MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
            if(metodoPagoDAO.eliminar(Integer.parseInt(txtIdMetodoPago.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Metodo Pago Eliminado");
                limpiarControles();
                txtIdMetodoPago.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró metodo pago para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMetodoPagoActionPerformed

    private void btnModificarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMetodoPagoActionPerformed
        // TODO add your handling code here:
        try {
            MetodoPago metodoPago = new MetodoPago();
            MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
            
            metodoPago.setId(Integer.parseInt(txtIdMetodoPago.getText()));
            metodoPago.setTipoPago(txtTipoPago.getText());
            metodoPagoDAO.modificar(metodoPago);
            JOptionPane.showMessageDialog(null, "Metodo Pago Modificado");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarMetodoPagoActionPerformed

    private void btnListarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarMetodoPagoActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
            String [] titulos = {"ID", "TIPO PAGO"};
            ArrayList<MetodoPago> lista = metodoPagoDAO.listarMetodoPago();
            for(MetodoPago metodoPago : lista) {
                matrizMetodoPago[fila][0] = String.valueOf(metodoPago.getId());
                matrizMetodoPago[fila][1] = metodoPago.getTipoPago();
                fila++;
            }
            modelo = new DefaultTableModel(matrizMetodoPago, titulos);
            tblMetodoPago.setModel(modelo);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarMetodoPagoActionPerformed

    private void tblMetodoPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMetodoPagoMouseClicked
        // TODO add your handling code here:
        int fila = tblMetodoPago.getSelectedRow();
        txtIdMetodoPago.setText(tblMetodoPago.getValueAt(fila, 0).toString());
        txtTipoPago.setText(tblMetodoPago.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblMetodoPagoMouseClicked

    public void limpiarControles() {
        txtIdMetodoPago.setText("");
        txtTipoPago.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMetodoPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMetodoPago;
    private javax.swing.JButton btnBuscarMetodoPago;
    private javax.swing.JButton btnEliminarMetodoPago;
    private javax.swing.JButton btnListarMetodoPago;
    private javax.swing.JButton btnModificarMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMetodoPago;
    private javax.swing.JTextField txtIdMetodoPago;
    private javax.swing.JTextField txtTipoPago;
    // End of variables declaration//GEN-END:variables
}
