/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author henrr
 */
public class JFPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuIdioma = new javax.swing.JMenuItem();
        menuEstado = new javax.swing.JMenuItem();
        menuEditorial = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuLibro = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuRegion = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuMetodoDePago = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jMenu1.setText("Mantenedores");

        jMenu4.setText("Libro");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(menuCategoria);

        menuIdioma.setText("Idioma");
        menuIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIdiomaActionPerformed(evt);
            }
        });
        jMenu4.add(menuIdioma);

        menuEstado.setText("Estado");
        menuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoActionPerformed(evt);
            }
        });
        jMenu4.add(menuEstado);

        menuEditorial.setText("Editorial");
        menuEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditorialActionPerformed(evt);
            }
        });
        jMenu4.add(menuEditorial);

        jMenuItem1.setText("Autor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuLibro.setText("Libro");
        menuLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLibroActionPerformed(evt);
            }
        });
        jMenu4.add(menuLibro);

        jMenu1.add(jMenu4);

        jMenu5.setText("Direccion");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        menuRegion.setText("Region");
        menuRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegionActionPerformed(evt);
            }
        });
        jMenu5.add(menuRegion);

        jMenuItem9.setText("Ciudad");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Comuna");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Direccion");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenu1.add(jMenu5);

        menuMetodoDePago.setText("Metodo de Pago");
        menuMetodoDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMetodoDePagoActionPerformed(evt);
            }
        });
        jMenu1.add(menuMetodoDePago);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoActionPerformed
        // TODO add your handling code here:
        JFEstado jfEstado = new JFEstado();
        jfEstado.setVisible(true);
    }//GEN-LAST:event_menuEstadoActionPerformed

    private void menuIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIdiomaActionPerformed
        // TODO add your handling code here:
        JFIdioma jFIdioma = new JFIdioma();
        jFIdioma.setVisible(true);
    }//GEN-LAST:event_menuIdiomaActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        // TODO add your handling code here:
        JFCategoria jfCategoria = new JFCategoria();
        jfCategoria.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegionActionPerformed
        // TODO add your handling code here:
        JFRegion jfRegion = new JFRegion();
        jfRegion.setVisible(true);
    }//GEN-LAST:event_menuRegionActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JFCiudad jfCiudad = new JFCiudad();
        jfCiudad.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        JFComuna jfComuna = new JFComuna();
        jfComuna.setVisible(true);
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JFDireccion jfDireccion = new JFDireccion();
        jfDireccion.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void menuEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditorialActionPerformed
        // TODO add your handling code here:
        JFEditorial jfEditoral = new JFEditorial();
        jfEditoral.setVisible(true);
    }//GEN-LAST:event_menuEditorialActionPerformed

    private void menuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLibroActionPerformed
        // TODO add your handling code here:
        JFLibro jfLibro = new JFLibro();
        jfLibro.setVisible(true);
    }//GEN-LAST:event_menuLibroActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        JFMetodoPago metodoPago = new JFMetodoPago();
        metodoPago.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        JFComuna jfComuna = new JFComuna();
        jfComuna.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuMetodoDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMetodoDePagoActionPerformed
        // TODO add your handling code here:
        JFMetodoPago metodoPago = new JFMetodoPago();
        metodoPago.setVisible(true);
    }//GEN-LAST:event_menuMetodoDePagoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFAutor autor = new JFAutor();
        autor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuEditorial;
    private javax.swing.JMenuItem menuEstado;
    private javax.swing.JMenuItem menuIdioma;
    private javax.swing.JMenuItem menuLibro;
    private javax.swing.JMenuItem menuMetodoDePago;
    private javax.swing.JMenuItem menuRegion;
    // End of variables declaration//GEN-END:variables
}
