/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.tda.dao.TelefonoDAO;
import biblioteca.tda.modelo.Telefono;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrr
 */
public class JFTelefono extends javax.swing.JFrame {
    String [][] matrizTelefono = new String[150][3];
    DefaultTableModel modelo;
    /**
     * Creates new form JFTelefono
     */
    public JFTelefono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroTelefono = new javax.swing.JTextField();
        btnAgregarTelefono = new javax.swing.JButton();
        btnBuscarTelefono = new javax.swing.JButton();
        btnEliminarTelefono = new javax.swing.JButton();
        btnModificarTelefono = new javax.swing.JButton();
        btnListarTelefono = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTelefonos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtIdListaTel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Telefono");

        jLabel2.setText("ID Telefono:");

        jLabel3.setText("Número:");

        btnAgregarTelefono.setText("Agregar");
        btnAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTelefonoActionPerformed(evt);
            }
        });

        btnBuscarTelefono.setText("Buscar");
        btnBuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTelefonoActionPerformed(evt);
            }
        });

        btnEliminarTelefono.setText("Eliminar");
        btnEliminarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTelefonoActionPerformed(evt);
            }
        });

        btnModificarTelefono.setText("Modificar");
        btnModificarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTelefonoActionPerformed(evt);
            }
        });

        btnListarTelefono.setText("Listar");
        btnListarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTelefonoActionPerformed(evt);
            }
        });

        tblTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NUMERO", "LISTA_TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(tblTelefonos);

        jLabel4.setText("ID Lista Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdTelefono)
                            .addComponent(txtNumeroTelefono)
                            .addComponent(txtIdListaTel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addGap(271, 271, 271))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnAgregarTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarTelefono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdListaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTelefono)
                    .addComponent(btnBuscarTelefono)
                    .addComponent(btnEliminarTelefono)
                    .addComponent(btnModificarTelefono)
                    .addComponent(btnListarTelefono))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTelefonoActionPerformed
        // TODO add your handling code here:
        try {
            Telefono telefono = new Telefono();
            TelefonoDAO telefonoDAO = new TelefonoDAO();
            
            telefono.setId(Integer.parseInt(txtIdTelefono.getText()));
            telefono.setNumero(txtNumeroTelefono.getText());
            telefono.setListaNumeros(Integer.parseInt(txtIdListaTel.getText()));
            telefonoDAO.insertar(telefono);
            JOptionPane.showMessageDialog(null, "Telefono ingresado");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarTelefonoActionPerformed

    private void btnBuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTelefonoActionPerformed
        // TODO add your handling code here:
        try {
            TelefonoDAO telefonoDAO = new TelefonoDAO();
            Telefono telefono = telefonoDAO.buscar(Integer.parseInt(txtIdTelefono.getText()));
            if(telefono.getId() != 0) {
                txtNumeroTelefono.setText(telefono.getNumero());
                txtIdTelefono.setText(String.valueOf(telefono.getListaNumeros()));
            } else {
                JOptionPane.showMessageDialog(null, "Telefono no encontrado");
                txtIdTelefono.requestFocus();
                limpiarControles();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarTelefonoActionPerformed

    private void btnEliminarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTelefonoActionPerformed
        // TODO add your handling code here:
        try {
            TelefonoDAO telefonoDAO = new TelefonoDAO();
            if(telefonoDAO.eliminar(Integer.parseInt(txtIdTelefono.getText())) != 0) {
                JOptionPane.showMessageDialog(null, "Telefono Eliminado");
                limpiarControles();
                txtIdTelefono.requestFocus();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarTelefonoActionPerformed

    private void btnModificarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTelefonoActionPerformed
        // TODO add your handling code here:
        try {
            Telefono telefono = new Telefono();
            TelefonoDAO telefonoDAO = new TelefonoDAO();
            telefono.setId(Integer.parseInt(txtIdTelefono.getText()));
            telefono.setNumero(txtNumeroTelefono.getText());
            telefono.setListaNumeros(Integer.parseInt(txtIdListaTel.getText()));
            telefonoDAO.modificar(telefono);
            JOptionPane.showMessageDialog(null, "Telefono Modificado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarTelefonoActionPerformed

    private void btnListarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTelefonoActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            TelefonoDAO telefonoDAO = new TelefonoDAO();
            String[] titulos = {"ID", "NUMERO", "LISTA_TELEFONO"};
            ArrayList<Telefono> lista = telefonoDAO.listar();
            for(Telefono telefono : lista) {
                matrizTelefono[fila][0] = String.valueOf(telefono.getId());
                matrizTelefono[fila][1] = telefono.getNumero();
                matrizTelefono[fila][2] = String.valueOf(telefono.getListaNumeros());
                fila++;
            }
            modelo = new DefaultTableModel(matrizTelefono, titulos);
            tblTelefonos.setModel(modelo);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarTelefonoActionPerformed

    public void limpiarControles() {
        txtIdTelefono.setText("");
        txtNumeroTelefono.setText("");
        txtIdListaTel.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTelefono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTelefono;
    private javax.swing.JButton btnBuscarTelefono;
    private javax.swing.JButton btnEliminarTelefono;
    private javax.swing.JButton btnListarTelefono;
    private javax.swing.JButton btnModificarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTelefonos;
    private javax.swing.JTextField txtIdListaTel;
    private javax.swing.JTextField txtIdTelefono;
    private javax.swing.JTextField txtNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
